version: '3.7'

services:
  socket-api:
    build:
      context: .
      target: development
    volumes:
      - /srv/app/dist
      - /srv/app/node_modules
      - .:/srv/app
    ports:
      - ${PORT}:${PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - socket-network
    depends_on:
      - socket-redis
  socket-redis:
    image: redis:5
    networks:
      - socket-network
networks:
  socket-network:
volumes:
  socket-pgdata: