// Redis constants
export const REDIS_SUBSCRIBER_CLIENT = 'REDIS_SUBSCRIBER_CLIENT';
export const REDIS_PUBLISHER_CLIENT = 'REDIS_PUBLISHER_CLIENT';

// Redis events
export const REDIS_SOCKET_EVENT_SEND_NAME = 'REDIS_SOCKET_EVENT_SEND_NAME';
export const REDIS_SOCKET_EVENT_EMIT_SPECIFIC_AUTH = 'REDIS_SOCKET_EVENT_EMIT_SPECIFIC_AUTH';
export const REDIS_SOCKET_EVENT_EMIT_ALL_AUTH = 'REDIS_SOCKET_EVENT_EMIT_ALL_AUTH';
